# Generated by Django 3.2.5 on 2021-07-12 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=50)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('prev_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('prev_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('percent_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historical_Stock_Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recorded', models.DateTimeField()),
                ('price_open', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_close', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data_id', to='portfolio_test.stock')),
            ],
        ),
    ]
