# Generated by Django 3.2.5 on 2021-07-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
