# Generated by Django 3.2.5 on 2021-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_test', '0004_auto_20210712_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_stock_data',
            name='price_close',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historical_stock_data',
            name='price_high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historical_stock_data',
            name='price_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historical_stock_data',
            name='price_open',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historical_stock_data',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prev_high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prev_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
