# Generated by Django 3.2.5 on 2021-07-12 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_test', '0005_auto_20210712_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_stock_data',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_forecast_id', to='portfolio_test.stock'),
        ),
        migrations.CreateModel(
            name='Forecast_Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('yhat', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('yhat_upper', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('yhat_lower', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data_id', to='portfolio_test.stock')),
            ],
        ),
    ]
