# Generated by Django 3.2.5 on 2021-07-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_test', '0006_auto_20210712_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='yhat_180',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_180_advice',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_180_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_180_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_30',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_30_advice',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_30_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_30_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_365',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_365_advice',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_365_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yhat_365_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
