# Generated by Django 3.2.5 on 2021-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_test', '0007_auto_20210713_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='yhat_180_advice',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yhat_30_advice',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yhat_365_advice',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
