# Generated by Django 3.2.5 on 2021-07-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='trans_date',
            new_name='date',
        ),
    ]
